flowchart TD
   O(fas:fa-user Owner)
   S(fas:fa-user Security Service provider)
   I(fas:fa-user Integrator)
   D(fas:fa-user Platform DevOps)
   P[fas:fa-server / fas:fa-cloud Platform]
   C[fas:fa-video Camera]
   CC[fas:fa-cloud Axis cloud connect]
   P --- CC
   I --> | fas:fa-wrench Setup | CC
%%   I --> | fas:fa-wrench Setup | P
   CC --> C
   O --> |Consent| CC
   S --- |Video| P
   O --- | Agreement | I
   I ---- | Agreement | S
   D --- P
   D --- | Agreement | CC
   S ---- | Agreement | D
   linkStyle 0,3 stroke:skyblue,stroke-width:4;
